### ISSUE TITLE
placeholderlabel  and TextField is mess together 

### ISSUE THREAD

**Issue by decormatters** [oleghnidets/TweeTextField#1]
## What did you do?
I want to display placeholderlabel and TextField.text 

ℹ Please replace this with what you did.  
usernameTextField.text = "alex"

## What happened instead?
placeholderlabel  and TextField is mess together ,

ℹ Actual results. Please replace this with of what happened instead. 

## What did you expect?
placeholderlabel  is upon TextField

ℹ Expected results. Please replace this with what you expected.  

## Environment
ios 11, xcode 9

**Comment by decormatters** [comment]
is it good to  make minimizePlaceholder public ?,  then can solve this by usernameTextField.minimizePlaceholder()

**Comment by oleghnidets** [comment]
Thanks for reporting ;) Fix that. Please, check it out. If you will have the problem let me know.
https://github.com/oleghnidets/TweeTextField/releases/tag/1.0.1
