### ISSUE TITLE
showInfo Multiple Line

### ISSUE THREAD

**Issue by alielephant** [oleghnidets/TweeTextField#10]
I have a long error message which i want to display under the textfield.

Is it possible to make the text continue on the next line? 

<img width="363" alt="screen shot 2018-03-25 at 3 08 03 pm" src="https://user-images.githubusercontent.com/29601129/37874787-714c95b8-303e-11e8-8a00-c227d020829e.png">

**Comment by oleghnidets** [comment]
Hi,
Sure, you can. There is public variable `infoLabel`. Just change `numberOfLines` value.
