### ISSUE TITLE
Framework via Carthage ins't working

### ISSUE THREAD

**Issue by damien-nd** [oleghnidets/TweeTextField#13]
## What did you do?

ℹ When I use Carthage to install the framework, everything is empty. If I do the same thing with CocoaPods, everything is working as expected. 

## What happened instead?

ℹ Framework is empty or have nothing open / public to access in.

## What did you expect?

ℹ Access to TweeTextField classes as it is with a CocoaPods install.

## Environment

- **Library version: 1.2.0**
- **Xcode version: 9.4.1**
- **Swift version: 4.1**
- **Platform running (iOS version): Simulator (iOS 11.4)**

**Comment by oleghnidets** [comment]
Hi,
I believe it has been fixed. Please, try again.
Let me know if it works for you.

**Comment by damien-nd** [comment]
Hi and thanks.

It works perfectly, just one more thing ;)

In the framework "Deployment Target" you forget to switch 11.4 to 9.0.
With that it is working.

And I forget to thanks you for your really nice work, it looks so cool.

**Comment by loicgriffie** [comment]
@damien-nd about deployement target issue, I just made a pull request to fix that along with some @IBDesignable private(set)

**Comment by oleghnidets** [comment]
Sorry huys. My bad. 
Thank you @loicgriffie for your PR.

**Comment by oleghnidets** [comment]
Merged and published. Please, let me know the results :)

**Comment by loicgriffie** [comment]
@oleghnidets it's working as expected 👍
