### ISSUE TITLE
Placeholder overlay with set text when the text is set in Interface builder

### ISSUE THREAD

**Issue by johnny77221** [oleghnidets/TweeTextField#15]
This bug is kind of like #8 mentioned, but now it's in case when I set text in interface builder
it's fine when I set the text programmically, but it would be good if you can fix this.

## What did you do?
set both text and placeholder in interface builder

## What happened instead?
Text and placeholder displayed, placeholder didn't move up

## What did you expect?
expected placeholder moved up since text is set  

## Environment

- Library version: 1.2.2
- Xcode version: 10 beta 2
- Swift version: 4.0 (main project is using 4.2 with specified swift_version=4.0 in Podfile post_install area)
- Platform running (iOS version): 12.0 on iPhone 8 simulator

## Demo Project

ℹ (Optional) Please link to or upload a project I can download that reproduces the issue.

**Comment by oleghnidets** [comment]
Hi,
I believe I have fixed that. 
Could you please test it by yourself?

`pod 'TweeTextField', :git => 'https://github.com/oleghnidets/TweeTextField.git', :branch => 'master'`

**Comment by johnny77221** [comment]
Your patch works, thanks!

for whom concerned, the build 01c233e has solved this problem without crashing

**Comment by oleghnidets** [comment]
Fix in [1.3.0](https://github.com/oleghnidets/TweeTextField/releases/tag/1.3.0)
