### ISSUE TITLE
Problems when changing orientations

### ISSUE THREAD

**Issue by Idomo** [oleghnidets/TweeTextField#16]
## What did you do?

Changed the device orientation to `landscape` and back to `portrait` when the `TweeAttributedTextField` was in focus (when the keyboard is showing-up).

## What happened instead?

The `TweeAttributedTextField` height is increased by x2 and the placeholder became to the middle of the `TweeAttributedTextField`.

## What did you expect?

The `TweeAttributedTextField` should stay the same and the placeholder should re-calculate it's position and be above the `TweeAttributedTextField`.

## Environment

- **Library version:** 1.2.2
- **Xcode version:** 9.4.1
- **Swift version:** 4.1.2
- **Platform running (iOS version):** 11.4

**Comment by oleghnidets** [comment]
Thanks. I will try to fix it asap :)

**Comment by oleghnidets** [comment]
Hi,
May you try `pod 'TweeTextField', :git => 'https://github.com/oleghnidets/TweeTextField/TweeTextField.git', :branch => 'master'` ?

BTW, did you use a height constraint?

**Comment by Idomo** [comment]
@oleghnidets I'll try it soon.
Not that I remember, Why?

**Comment by Idomo** [comment]
@oleghnidets The code didn't work, when running `pod install` it doesn't recognize the library (just not including it in the libraries list).

**Comment by oleghnidets** [comment]
Please, try this one `pod 'TweeTextField', :git => 'https://github.com/oleghnidets/TweeTextField.git', :branch => 'master'`

**Comment by Idomo** [comment]
@oleghnidets Same problem...

**Comment by oleghnidets** [comment]
[Sample.zip](https://github.com/oleghnidets/TweeTextField/files/2197414/Sample.zip)

For me it works.

**Comment by Idomo** [comment]
@oleghnidets Now it's working!
The problem that I'm facing with now is that the placeholder label leading constraint is `0` so it's not looking good, may you change this to `8` so it will look better?

And one more **important** thing, Please wrap placeholder text with NSLocalizedString() so it will be localizable.

**Comment by Idomo** [comment]
@oleghnidets suggestion about the spacing problem, maybe you should make the constraints equal to the `UITextField.leftView` so it will be possible to add `leftView` before the placeholder.

**Comment by oleghnidets** [comment]
Thanks a lot for your help. 
I will change it.

**Comment by Idomo** [comment]
@oleghnidets I'v just fixed the spacing problems (not including the leftView problem), see #17 
I'd like you to update when the localization will be implement.

**Comment by oleghnidets** [comment]
Fix in https://github.com/oleghnidets/TweeTextField/commit/8df9d93e5bff81042b89521afe8a93b6865ac254

Release is coming soon :)

**Comment by oleghnidets** [comment]
Done in [1.3.1](https://github.com/oleghnidets/TweeTextField/releases/tag/1.3.1)
