### ISSUE TITLE
Notification Center KeyboardWillHide/Show

### ISSUE THREAD

**Issue by alexdimcevski** [oleghnidets/TweeTextField#18]
## What did you do?

Two observers `NSNotification.Name.UIKeyboardWillShow` and `.UIKeyboardWillHide` share the same selector `keyboardDidChange(notification:)`. Which moves UILabels coordinates depending on if keyboard is showing or not.

## What happened instead?

The code in `keyboardDidChange(notification:)` is being rung every-time the TweeTextField is tapped on but my UI only updates after 2 taps on the same TweeTextField not 1 as intended. 

## What did you expect?

Expected the UILabel to change coordinate every-time TweeTextField shows or hides keyboard. 
My `keyboardDidChange(notification:)` works perfectly fine on a UITextfield but not on a `TweeAttributedTextField`.

## Environment

- **Library version: 1.2.2**
- **Xcode version: 9.4**
- **Swift version:** *4.1*
- **Platform running (iOS version): 10.13.3 **

**Comment by oleghnidets** [comment]
Hi there,
I want to help you, but I am not sure that I understood you correctly. Could you, please, attach example project?

**Comment by oleghnidets** [comment]
I am closing the issue as a response wasn't received. 
Issue may be re-opened if it makes sense and the bug is obvious.
