### ISSUE TITLE
Not able to create a subclass of this field

### ISSUE THREAD

**Issue by abdurrehmanio** [oleghnidets/TweeTextField#2]
## What did you do?

ℹ Please replace this with what you did.  

## What happened instead?

ℹ Actual results. Please replace this with of what happened instead. 

## What did you expect?

ℹ Expected results. Please replace this with what you expected.  

## Environment

- **Library version:**
- **Xcode version:**
- **Swift version:** *(if applicable, if not remove)*
- **Platform running (iOS version):**

## Demo Project

ℹ (Optional) Please link to or upload a project I can download that reproduces the issue.

**Comment by oleghnidets** [comment]
https://github.com/oleghnidets/TweeTextField/releases/tag/1.0.3

**Comment by abdurrehmanio** [comment]
Thanks for quick fix Oleg

**Comment by oleghnidets** [comment]
No probs ;)
