### ISSUE TITLE
AutoLayout crashes in the recent commits

### ISSUE THREAD

**Issue by johnny77221** [oleghnidets/TweeTextField#21]
## What did you do?
Updated to Xcode 10 beta 5

## What happened instead?
The layout manager crashed on runtime
with message 'Unable to activate constraint with anchors' 
either on viewDidLoad or when the field become editing

## What did you expect?
work without crashing

## Environment

- **Library version:** branch: master (should be commit b49c32bc7270167417f32820e7353e9f1fdf65fa )
- **Xcode version:** 10.0 beta 5
- **Swift version:** *(if applicable, if not remove)* 4.0
- **Platform running (iOS version):** iOS 12 beta 6

## Demo Project

ℹ (Optional) Please link to or upload a project I can download that reproduces the issue.

Note: I specify the build to commit 01c233ede811a7bb7e8ba7e3d0b5d83b44e1300d and the crash disappears

**Comment by oleghnidets** [comment]
Sorry, man. I will take a look ASAP.
I have lack of time :(

**Comment by johnny77221** [comment]
You’ve made a great job and saves everybody’s time, no need to be sorry :)

**Comment by oleghnidets** [comment]
Cannot currently check the issue. Waiting for official release of Xcode 10.

**Comment by RaminderSinghiBay** [comment]
Still crashes, even after downloading it and manually adding it project.

**Comment by Birju-Bhatt** [comment]
I am facing same issue. Any update guys ?

**Comment by oleghnidets** [comment]
Sorry guys, have lack of time now. 
I plan to start working on all issues these weekend. But if you want you can make PR, I review and merge it.

**Comment by johnny77221** [comment]
I think I found the problem...
the nil check should also apply to
enablePlaceholderHeightConstraint func

@Birju-Bhatt @RaminderSinghiBay 
Would you help try out my version before merging?
```
pod 'TweeTextField', git:'https://github.com/johnny77221/TweeTextField.git', commit:'87d6580'
```

**Comment by oleghnidets** [comment]
I will post release of 1.5.1 a bit later.
