### ISSUE TITLE
Leaks

### ISSUE THREAD

**Issue by johnny77221** [oleghnidets/TweeTextField#22]
## What did you do?
Setup textfield in interface builder with a button to remove the textfield at runtime 
(removeFromSuperview and set the pointer to nil)

## What happened instead?
The Debug Memory Graph ( or instruments ) shows the textfield is still alive

## What did you expect?
expect to be released

## Environment

- **Library version:** 01c233ede811a7bb7e8ba7e3d0b5d83b44e1300d and f46e84c  
- **Xcode version:** 10.0beta5 & 6
- **Swift version:** 4.0
- **Platform running (iOS version):** iOS 12 beta 8

## Demo Project

ℹ (Optional) Please link to or upload a project I can download that reproduces the issue.

**Comment by oleghnidets** [comment]
Good input. Thanks. The reason is CADisplayLink. I am working on this.

**Comment by oleghnidets** [comment]
Fixed in 1.4.0. 🤔
