### ISSUE TITLE
Change font of the placeholder label

### ISSUE THREAD

**Issue by dfmarulanda** [oleghnidets/TweeTextField#28]
## What did you do?

I tried to change the font of the placeholder directly but it didn't worked
` usernameTextField.placeholderLabel.font = UIFont(name: "Avenir-Heavy", size: 12.0)`
So i decided to create a subclass and override the font variable
```swift
class CRWTextField: TweeAttributedTextField {
  open override var font: UIFont? {
    get { return UIFont(name: "Avenir-Heavy", size: 12.0) }
    set { super.font =  UIFont(name: "Avenir-Heavy", size: 12.0) }
  }
}
```

## What happened instead?
The font of the label was changed but now the text is very near the bottom line; as seen in the image:
![IMG_0095](https://user-images.githubusercontent.com/2466498/54793162-21650600-4c0f-11e9-9ba1-48561c0725e3.png)

## What did you expect?

ℹ Expected results. Please replace this with what you expected.  

## Environment

- **Library version:Lastest
- **Xcode version:10.1
- **Swift version: 4.2
- **Platform running (iOS version): iOS 12

**Comment by dfmarulanda** [comment]
I think that's also changing me the font of the text.

**Comment by oleghnidets** [comment]
Hi,
Could you, please, make a screenshot in Debug View Hierarchy mode?

**Comment by dfmarulanda** [comment]
Is there a way to change only the text field placeholder label font?

**Comment by dfmarulanda** [comment]
Here you have the screens:
Email field, without custom font works ok, username field seems weird,.

![Screen Shot 2019-03-22 at 12 16 02 PM](https://user-images.githubusercontent.com/2466498/54841006-4b183e80-4c9c-11e9-9430-0909abcea7b1.png)
![Screen Shot 2019-03-22 at 12 15 20 PM](https://user-images.githubusercontent.com/2466498/54841007-4b183e80-4c9c-11e9-8dd7-2b3898c315fd.png)
![Screen Shot 2019-03-22 at 12 15 08 PM](https://user-images.githubusercontent.com/2466498/54841008-4b183e80-4c9c-11e9-9d40-fe0ee387c35b.png)

**Comment by dfmarulanda** [comment]
This guy seemed to have the same problem: https://github.com/mihailsalari/TweeTextField/commit/c1075aec5e1adcc6dae1c3be882ff3f72bec0994

**Comment by oleghnidets** [comment]
> Is there a way to change only the text field placeholder label font?

Hi,
Yes, you can access via `placeholderLabel` in TweePlaceholderTextField. Regarding your issue, you may update field' height so it can help.
I am developing a feature that enables support to add custom offset for bottom line: line width and line offset at the bottom.

**Comment by oleghnidets** [comment]
Release 1.5.2 should help you fix your issue. 
Thanks
