### ISSUE TITLE
Not working with generic tableview

### ISSUE THREAD

**Issue by pushpankq** [oleghnidets/TweeTextField#29]
## What did you do?

ℹ Please replace this with what you did.  

## What happened instead?

ℹ Actual results. Please replace this with of what happened instead. 

## What did you expect?

ℹ Expected results. Please replace this with what you expected.  

## Environment

- **Library version:**
- **Xcode version:**
- **Swift version:** *(if applicable, if not remove)*
- **Platform running (iOS version):**

## Demo Project

ℹ (Optional) Please link to or upload a project I can download that reproduces the issue.

**Comment by oleghnidets** [comment]
Sorry, you issue is not described and is not clear for me. Please, fill in issue template.
