### ISSUE TITLE
Add SPM support

### ISSUE THREAD

**Issue by rpolenthon** [oleghnidets/TweeTextField#30]
Hi, thanks for sharing this project. Maybe you could integrate SwiftPackageManager Support in the future? Since Xcode 11 supports it natively in the UI it will may be used more often in the future.

**Comment by oleghnidets** [comment]
Hi, 
Good input . Will do that for sure 💪

**Comment by rpolenthon** [comment]
Great

**Comment by oleghnidets** [comment]
Hi there,
Sorry for late response.

I added support of SPM. Please, try it out and let me know. If you will have any problem just reopen the issue :)

**Comment by rpolenthon** [comment]
Nice, thanks.

**Comment by oleghnidets** [comment]
You are welcome ;)
