### ISSUE TITLE
ShowInfo option not visible

### ISSUE THREAD

**Issue by NaveenReddy1** [oleghnidets/TweeTextField#31]
I am not getting the option for showInfo, I just followed the doc. Also I am using objective c.

**Comment by NaveenReddy1** [comment]
Any update?

**Comment by oleghnidets** [comment]
I will take a look. Sorry, currently have a bit lack of time :(

**Comment by raphaelmsr** [comment]
Same here! Very strange behaviour, Obj-C as well

**Comment by oleghnidets** [comment]
Hi,
Could you, please, get more details? Library version, iOS version, Xcode version, Swift? Had it worked before? 

I launched sample project and it works. (you may find it in repository)

**Comment by raphaelmsr** [comment]
Last version of the library
iOS 13.3.1/13.4 but not related
Xcode 11.4
Objective-C project

**Comment by oleghnidets** [comment]
Please, check this out https://github.com/oleghnidets/TweeTextField/releases/tag/1.6.2

If you have any question or issues reopen this issue.
