### ISSUE TITLE
Add support to manage gap between placeholder label and entered text. 

### ISSUE THREAD

**Issue by abdurrehmanio** [oleghnidets/TweeTextField#32]
## What did you do?

ℹ Please replace this with what you did.  

## What happened instead?

ℹ Actual results. Please replace this with of what happened instead. 

## What did you expect?

ℹ Expected results. Please replace this with what you expected.  

## Environment

- **Library version:**
- **Xcode version:**
- **Swift version:** *(if applicable, if not remove)*
- **Platform running (iOS version):**

## Demo Project

ℹ (Optional) Please link to or upload a project I can download that reproduces the issue.

**Comment by oleghnidets** [comment]
Hi @abdurrehmanio ,

Please, describe the reason. As I am not sure whether it is really needed.

**Comment by oleghnidets** [comment]
Done :)

https://github.com/oleghnidets/TweeTextField/releases/tag/1.6.3

**Comment by abdurrehmanio** [comment]
Thank you brother.

**Comment by gurpreetKobe** [comment]
How can we use this? @abdurrehmanio  @oleghnidets
