### ISSUE TITLE
Animated Placeholder inset issue when used left view

### ISSUE THREAD

**Issue by deepaksinghbora** [oleghnidets/TweeTextField#34]
## What did you do?

ℹ Added left view on textfield 

## What happened instead?

ℹ Actual results. leadingPlaceholderConstraint gets added with left view width

## What did you expect?

ℹ Expected results.  Place holder leading after and during animation should work as default

## Environment

- **Library version:** (1.6.3)
- **Xcode version:** 11.3.1
- **Swift version:** *(5)*
- **Platform running (iOS version): 12.4

## Demo Project

ℹ (Optional) Please link to or upload a project I can download that reproduces the issue.

**Comment by oleghnidets** [comment]
@deepaksinghbora Could you, please, revise a sample app? It has the text field with left and right views. 
Also, I'll appreciate if you provide some screenshots or video how it works for you.
