### ISSUE TITLE
can we hide info view on click of outside of active textfield

### ISSUE THREAD

**Issue by pramodshukla1011** [oleghnidets/TweeTextField#35]
## What did you do?

ℹ Please replace this with what you did.  

## What happened instead?

ℹ Actual results. Please replace this with of what happened instead. 

## What did you expect?

ℹ Expected results. Please replace this with what you expected.  

## Environment

- **Library version:**
- **Xcode version:**
- **Swift version:** *(if applicable, if not remove)*
- **Platform running (iOS version):**

## Demo Project

ℹ (Optional) Please link to or upload a project I can download that reproduces the issue.

**Comment by oleghnidets** [comment]
Hi there,
You can hide the info view by using `hideInfo`. Tapping outside can be done as [described here](https://stackoverflow.com/questions/24126678/close-ios-keyboard-by-touching-anywhere-using-swift).

Thanks for using library!
