### ISSUE TITLE
issue while installing using cocoapods

### ISSUE THREAD

**Issue by iamshezad** [oleghnidets/TweeTextField#4]
Analyzing dependencies
[!] Unable to find a specification for `TweeTextField`

**Comment by oleghnidets** [comment]
Hi,
I have no problem. Look attached.
Try to update cocoapods on your mac. 

<img width="726" alt="screen shot 2018-01-31 at 10 07 10" src="https://user-images.githubusercontent.com/7702033/35611753-c6b2d0de-066e-11e8-88d8-00af913e137a.png">


[Sample.zip](https://github.com/oleghnidets/TweeTextField/files/1680856/Sample.zip)

**Comment by iamshezad** [comment]
@oleghnidets sorry it was some issue with my cocoapods app.

**Comment by oleghnidets** [comment]
No prob :)
