### ISSUE TITLE
RTL language support

### ISSUE THREAD

**Issue by ghimireprashant** [oleghnidets/TweeTextField#6]
no support for RTL

**Comment by oleghnidets** [comment]
Good point 👍🏻

**Comment by oleghnidets** [comment]
Check the latest [release](https://github.com/oleghnidets/TweeTextField/releases/tag/1.1.0). 
Let me know whether it works for you.

**Comment by ghimireprashant** [comment]
![simulator screen shot - iphone 8 plus - 2018-02-20 at 18 02 40](https://user-images.githubusercontent.com/16249616/36423510-50814daa-1668-11e8-9b24-d807d021bf3b.png)
still no change while changing to RTL

**Comment by oleghnidets** [comment]
Because you are writing in English. Try to write in Arabic.
It is default behavior of UITextField.

**Comment by ghimireprashant** [comment]
everything is fine but the side to Start to write must start from right now its from left side.ie like floating label while is in right side.

**Comment by oleghnidets** [comment]
Man, it is default behavior of UITextField. Try to type in Arabic and you will see that it begins from right. 
I won't implement special logic for this.

**Comment by ghimireprashant** [comment]
thank you mate I checked it and its really work when I change the keyboard.thank you once again mate you are life saver

**Comment by oleghnidets** [comment]
Thanks 🙂 Glad to hear that everything is good.

**Comment by ghimireprashant** [comment]
while using swift 3.2 I am facing one problem. my floating placeholder is
not displaying in 3.2 can you help me.

  let centerYConstraint = placeholderLabel.centerYAnchor.constraint(equalTo:
centerYAnchor)

    centerYConstraint.priority = 1000

    centerYConstraint.isActive = true
