### ISSUE TITLE
Set the text on the right side 

### ISSUE THREAD

**Issue by TimaShams** [oleghnidets/TweeTextField#7]
How can I set the placeholder text on the right side?

**Comment by oleghnidets** [comment]
Good question. I think it can be nice improvement. 
I will implement like default behavior of UITextField' placeholder - when you set `Alignment` to right the placeholder is at the right too.

**Comment by oleghnidets** [comment]
As temporary solutions set `Semantic` to `Force Right-To-Left` and text `Alignment` to `right`.

**Comment by oleghnidets** [comment]
Please, try `pod 'TweeTextField', :git => 'https://github.com/oleghnidets/TweeTextField.git', :commit => '5039ae25e0e' ` and let me know whether it works for you.
Thanks

**Comment by 0xKayvan** [comment]
@oleghnidets the commit `5039ae25e0e` works for RTL languages ;)

**Comment by oleghnidets** [comment]
Thanks for letting me know. I will post release today!

**Comment by oleghnidets** [comment]
Fixed in 1.2.0 release.
Cheers
