### ISSUE TITLE
multiple lines

### ISSUE THREAD

**Issue by alielephant** [oleghnidets/TweeTextField#9]
is it possible to add multiple lines to the TweeAttributedTextField class?

**Comment by oleghnidets** [comment]
Hi,
Do you mean placeholder or text?

**Comment by alielephant** [comment]
My bad, I have to use UITextView instead of UITextField. Will you support UITextField by any chance in the future?

**Comment by oleghnidets** [comment]
Yeah, it can be great improvement. 
For now I close the issue but I will keep in mind to make the same with `UITextView`.

**Comment by asifbilal786** [comment]
Please add support for UITextView as well as it's really needed here.
